# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0afa7a2e8dfa8197a5c45f0ced8a20d32ef1b81b46259ff79dabcd349970b222c30a0f2e609d953b718d6a54d8137374692936004e9ed5b23784961397e50f9

test:
  secret_key_base: 88797e7014f505b71c9f187f33fcb7ba5b08e40982923c6f17a5daf8b807aa081ea14d682102d6795801a178fa21c8a507727e0a8c9ec24a0e48fd6030d8014a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
